version: '3.4'

services:
  dynamodb:
    image: amazon/dynamodb-local
    restart: always
    ports:
      - "8000:8000"
    environment:
      AWS_ACCESS_KEY_ID: root
      AWS_SECRET_ACCESS_KEY: secret