version: "3"
services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_db:/var/lib/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
  node-exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"
  cadvisor:
    image: google/cadvisor:latest
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
  pushgateway:
    image: prom/pushgateway
    ports:
      - "9091:9091"
  grafana:
    image: grafana/grafana:7.5.3
    user: "1000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secure_pass
    volumes:
      - ./grafana_db:/var/lib/grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
  # reports:
  #   image: skedler/reports:latest
  #   container_name: reports
  #   privileged: true
  #   cap_add:
  #     - SYS_ADMIN
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #     - reportdata:/var/lib/skedler
  #     - ./reporting.yml:/opt/skedler/config/reporting.yml
  #   ports:
  #     - 3001:3001
