global:
  scrape_interval: 5s
  external_labels:
    monitor: "devopsage-monitor"
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["10.0.0.204:9090"]
  - job_name: "node-exporter"
    static_configs:
      - targets: ["10.0.0.204:9100"]
  - job_name: "cAdvisor"
    static_configs:
      - targets: ["10.0.0.204:8080"]
  - job_name: "pushGateway"
    static_configs:
      - targets: ["10.0.0.204:9091"]
