version: '3.4'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    container_name: es_single_761
    environment:
      - discovery.type=single-node
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.1
    container_name: es_kibana_761
    volumes:
      - kibana_data:/usr/share/kibana/data
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
  metricbeat:
    image: docker.elastic.co/beats/metricbeat:7.6.1
    container_name: es_metricbeat_761
    user: root
    volumes:
      - metricbeat_data:/usr/share/metricbeat/data
      - ./metricbeat.yml:/usr/share/metricbeat/config/metricbeat.yml
    command: ["--strict.perms=false", "-system.hostfs=/hostfs"]
  apmserver:
    image: docker.elastic.co/apm/apm-server:7.6.1
    container_name: es_apmserver_761
    user: root
    volumes:
      - apmserver_data:/usr/share/apm-server/data
      - ./apm-server.yml:/usr/share/apm-server/apm-server.yml
    ports:
      - 8200:8200
  esheadplugin:
    image: mobz/elasticsearch-head:5
    container_name: es_head
    ports:
      - 9100:9100

volumes:
  elasticsearch_data:
    driver: local
  kibana_data:
    driver: local
  metricbeat_data:
    driver: local
  apmserver_data:
    driver: local