version: '3.4'

services:
  sql_server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Acesso_332"
      ACCEPT_EULA: "Y"